### ISSUE TITLE
Reloading with Nix on MacOS and potentially NixOS fully doesn't work.

### ISSUE THREAD

**Issue by Eveeifyeve** [drcika/apc-extension#177]
Hey just so you know for some reason nix support does really work and I see no issues based on this issue that is running nix n macOS. So I am wondering Is this a common issue with nix or apc-extension:
```
Apc Extension failed: Error: EACCES: permission denied, rename '/nix/store/wnb0aqmp8ic25xw15s441c6ngapyi3r5-vscode-1.88.0/Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-amd.js' -> '/nix/store/wnb0aqmp8ic25xw15s441c6ngapyi3r5-vscode-1.88.0/Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-amd.js.apc.extension.backup'
```
If it is apc can it be fixed and have documentation for those who are using Nix/NixOS Please?

**Comment by yorks-dev** [comment]
So basically the reason why its not working is because the installation folder for nix is not actually what you get using 'which code' command. If you ls -la in /Users/yourusername/.nix-profile/bin/, you will see that code is smlinked to  /nix/store/qi8zmyzn03xmsw45zqa4ansd0dvl2sah-vscode-1.89.0/bin/code.  You need to make it read writable. so, 

step 1 : cd /nix/store/qi8zmyzn03xmsw45zqa4ansd0dvl2sah-vscode-1.89.0/Applications/Visual\ Studio\ Code.app/Contents/Resources/app/out/

(the hash might vary for you but you can find it using 'which code' and ls -la . 

<img width="1361" alt="image" src="https://github.com/drcika/apc-extension/assets/63572464/bc7214de-8e40-40b1-98dc-a4932d0a4ed7">

now at /nix/store/qi8zmyzn03xmsw45zqa4ansd0dvl2sah-vscode-1.89.0/Applications/Visual\ Studio\ Code.app/Contents/Resources/app/out/ 

make it writable using 'chmod -R 777  /nix/store/qi8zmyzn03xmsw45zqa4ansd0dvl2sah-vscode-1.89.0/Applications/Visual\ Studio\ Code.app/Contents/Resources/app/out/' and you should be good to go.

it should look like : 
<img width="1361" alt="image" src="https://github.com/drcika/apc-extension/assets/63572464/192ba1ae-a7e6-425f-87a4-49b9330021d7">

thanks.

**Comment by Aetherall** [comment]
Hi ! new nixos user here. I encountered some trouble using that solution after following the link on https://github.com/drcika/apc-extension/issues/178. I am trying to work it out, and sharing my results along the way.

Nixos makes the nix store readonly. The recommanded way to patch a program in nix is to use an overlay to make a new derivation.

```nix
nixpkgs.overlays = [
  (self: super: {
     vscode = super.vscode.overrideAttrs (attrs: {
       patches = []; # Put patches here
     });
  })
];
```

This will override the build of pkgs.vscode to apply the patches

However, here, we are patching the built files using javascript, so we must rely on a different method. rather than using the patches property, we can use the postInstall property to execute a script

```nix
vscode = super.vscode.overrideAttrs (attrs: {
  postInstall = ''
    echo "test" > $out/test
  ''
});
```
Upon rebuild, we can see the test file in the readonly file system at the root of the vscode installation.

now to run the patch script, we have to execute javascript. To do so, we must add nodejs as a build input.

```nix
  nixpkgs.overlays = [
    (self: super: {
      vscode = super.vscode.overrideAttrs (attrs: {
        postInstall = ''
          node -e "console.log(42)" > $out/test
        '';
        buildInputs = attrs.buildInputs ++ [pkgs.nodejs];
      });
    })
  ];
```

Now I get 42 in the test file.

Now we must execute the patch itself.
After some time I got this working:

```nix
 nixpkgs.overlays = let
    apc-extension = builtins.fetchGit {
      url = https://github.com/drcika/apc-extension.git;
      rev = "d4cc908bf2869fe354aa0c103bab063aa09fd491";
    };
  in [
    (self: super: {
      vscode = super.vscode.overrideAttrs (attrs: {
        postInstall = ''
          cd $out
          mkdir apc-extension

          sed '1d' ${apc-extension}/src/patch.ts >> $out/apc-extension/patch.ts
          sed "s%require.main!.filename%'$out/lib/vscode/resources/app/out/dummy'%g" -i  $out/apc-extension/patch.ts
          sed "s%vscode.window.showErrorMessage(%throw new Error(installationPath + %g" -i  $out/apc-extension/patch.ts
          sed "s%promptRestart();%%g" -i  $out/apc-extension/patch.ts

          sed '1d' ${apc-extension}/src/utils.ts > $out/apc-extension/utils.ts
          ls $out/apc-extension >> log

          echo "import { install } from './patch.ts'; install({ extensionPath: '${apc-extension}' })" > $out/apc-extension/install.ts

          bun apc-extension/install.ts
        '';
        buildInputs = attrs.buildInputs ++ [
          pkgs.bun
        ];
      });
    })
  ];
```

In this current state, the patch is applied, but I still get the error referenced in another issue:

https://github.com/drcika/apc-extension/issues/184

```
TypeError: findVariable is not a function or its return value is not iterable
    at exports.style (classes.js:207:25)
    at y._invokeFactory (workbench.js:1395:29)
    at y.complete (workbench.js:1405:21)
```

I think i am nearly there, but cant get the styling to have any effect

**Comment by Eveeifyeve** [comment]
> Hi ! new nixos user here. I encountered some trouble using that solution after following the link on #178. I am trying to work it out, and sharing my results along the way.
> 
> Nixos makes the nix store readonly. The recommanded way to patch a program in nix is to use an overlay to make a new derivation.
> 
> ```nix
> nixpkgs.overlays = [
>   (self: super: {
>      vscode = super.vscode.overrideAttrs (attrs: {
>        patches = []; # Put patches here
>      });
>   })
> ];
> ```
> 
> This will override the build of pkgs.vscode to apply the patches
> 
> However, here, we are patching the built files using javascript, so we must rely on a different method. rather than using the patches property, we can use the postInstall property to execute a script
> 
> ```nix
> vscode = super.vscode.overrideAttrs (attrs: {
>   postInstall = ''
>     echo "test" > $out/test
>   ''
> });
> ```
> 
> Upon rebuild, we can see the test file in the readonly file system at the root of the vscode installation.
> 
> now to run the patch script, we have to execute javascript. To do so, we must add nodejs as a build input.
> 
> ```nix
>   nixpkgs.overlays = [
>     (self: super: {
>       vscode = super.vscode.overrideAttrs (attrs: {
>         postInstall = ''
>           node -e "console.log(42)" > $out/test
>         '';
>         buildInputs = attrs.buildInputs ++ [pkgs.nodejs];
>       });
>     })
>   ];
> ```
> 
> Now I get 42 in the test file.
> 
> Now we must execute the patch itself. After some time I got this working:
> 
> ```nix
>  nixpkgs.overlays = let
>     apc-extension = builtins.fetchGit {
>       url = https://github.com/drcika/apc-extension.git;
>       rev = "d4cc908bf2869fe354aa0c103bab063aa09fd491";
>     };
>   in [
>     (self: super: {
>       vscode = super.vscode.overrideAttrs (attrs: {
>         postInstall = ''
>           cd $out
>           mkdir apc-extension
> 
>           sed '1d' ${apc-extension}/src/patch.ts >> $out/apc-extension/patch.ts
>           sed "s%require.main!.filename%'$out/lib/vscode/resources/app/out/dummy'%g" -i  $out/apc-extension/patch.ts
>           sed "s%vscode.window.showErrorMessage(%throw new Error(installationPath + %g" -i  $out/apc-extension/patch.ts
>           sed "s%promptRestart();%%g" -i  $out/apc-extension/patch.ts
> 
>           sed '1d' ${apc-extension}/src/utils.ts > $out/apc-extension/utils.ts
>           ls $out/apc-extension >> log
> 
>           echo "import { install } from './patch.ts'; install({ extensionPath: '${apc-extension}' })" > $out/apc-extension/install.ts
> 
>           bun apc-extension/install.ts
>         '';
>         buildInputs = attrs.buildInputs ++ [
>           pkgs.bun
>         ];
>       });
>     })
>   ];
> ```
> 
> In this current state, the patch is applied, but I still get the error referenced in another issue:
> 
> #184
> 
> ```
> TypeError: findVariable is not a function or its return value is not iterable
>     at exports.style (classes.js:207:25)
>     at y._invokeFactory (workbench.js:1395:29)
>     at y.complete (workbench.js:1405:21)
> ```
> 
> I think i am nearly there, but cant get the styling to have any effect

I will give it a try on macos but I think there should be an offical way to get it working on nix

**Comment by Eveeifyeve** [comment]
> Hi ! new nixos user here. I encountered some trouble using that solution after following the link on #178. I am trying to work it out, and sharing my results along the way.
> 
> Nixos makes the nix store readonly. The recommanded way to patch a program in nix is to use an overlay to make a new derivation.
> 
> ```nix
> nixpkgs.overlays = [
>   (self: super: {
>      vscode = super.vscode.overrideAttrs (attrs: {
>        patches = []; # Put patches here
>      });
>   })
> ];
> ```
> 
> This will override the build of pkgs.vscode to apply the patches
> 
> However, here, we are patching the built files using javascript, so we must rely on a different method. rather than using the patches property, we can use the postInstall property to execute a script
> 
> ```nix
> vscode = super.vscode.overrideAttrs (attrs: {
>   postInstall = ''
>     echo "test" > $out/test
>   ''
> });
> ```
> 
> Upon rebuild, we can see the test file in the readonly file system at the root of the vscode installation.
> 
> now to run the patch script, we have to execute javascript. To do so, we must add nodejs as a build input.
> 
> ```nix
>   nixpkgs.overlays = [
>     (self: super: {
>       vscode = super.vscode.overrideAttrs (attrs: {
>         postInstall = ''
>           node -e "console.log(42)" > $out/test
>         '';
>         buildInputs = attrs.buildInputs ++ [pkgs.nodejs];
>       });
>     })
>   ];
> ```
> 
> Now I get 42 in the test file.
> 
> Now we must execute the patch itself. After some time I got this working:
> 
> ```nix
>  nixpkgs.overlays = let
>     apc-extension = builtins.fetchGit {
>       url = https://github.com/drcika/apc-extension.git;
>       rev = "d4cc908bf2869fe354aa0c103bab063aa09fd491";
>     };
>   in [
>     (self: super: {
>       vscode = super.vscode.overrideAttrs (attrs: {
>         postInstall = ''
>           cd $out
>           mkdir apc-extension
> 
>           sed '1d' ${apc-extension}/src/patch.ts >> $out/apc-extension/patch.ts
>           sed "s%require.main!.filename%'$out/lib/vscode/resources/app/out/dummy'%g" -i  $out/apc-extension/patch.ts
>           sed "s%vscode.window.showErrorMessage(%throw new Error(installationPath + %g" -i  $out/apc-extension/patch.ts
>           sed "s%promptRestart();%%g" -i  $out/apc-extension/patch.ts
> 
>           sed '1d' ${apc-extension}/src/utils.ts > $out/apc-extension/utils.ts
>           ls $out/apc-extension >> log
> 
>           echo "import { install } from './patch.ts'; install({ extensionPath: '${apc-extension}' })" > $out/apc-extension/install.ts
> 
>           bun apc-extension/install.ts
>         '';
>         buildInputs = attrs.buildInputs ++ [
>           pkgs.bun
>         ];
>       });
>     })
>   ];
> ```
> 
> In this current state, the patch is applied, but I still get the error referenced in another issue:
> 
> #184
> 
> ```
> TypeError: findVariable is not a function or its return value is not iterable
>     at exports.style (classes.js:207:25)
>     at y._invokeFactory (workbench.js:1395:29)
>     at y.complete (workbench.js:1405:21)
> ```
> 
> I think i am nearly there, but cant get the styling to have any effect

I got this when running on nix on darwin @Aetherall:
```
evaling implicit 'postInstall' string hook
243 |     patchBootstrap(extensionPath);
244 |     patchMain(extensionPath);
245 |     patchWorkbench(extensionPath);
246 | 
247 |   } catch (e) {
248 |     throw new Error(installationPath + `Apc Extension failed: ${e}`);
                ^
error: /nix/store/zbrndhqrchg0hbznqbmr7aqc8j3f9pd2-vscode-1.91.0/lib/vscode/resources/app/outApc Extension failed: ENOENT: No such fi
le or directory
      at /nix/store/zbrndhqrchg0hbznqbmr7aqc8j3f9pd2-vscode-1.91.0/apc-extension/patch.ts:248:11
      at install (/nix/store/zbrndhqrchg0hbznqbmr7aqc8j3f9pd2-vscode-1.91.0/apc-extension/patch.ts:240:31)
      at /nix/store/zbrndhqrchg0hbznqbmr7aqc8j3f9pd2-vscode-1.91.0/apc-extension/install.ts:1:39

Bun v1.1.17 (macOS arm64)
/nix/store/89ghmy7qxyggz4sycc9qr1klinmrlgbx-stdenv-darwin/setup: line 202: pop_var_context: head of shell_variables not a function co
ntext
```

**Comment by pink10000** [comment]
Any progress since then?

**Comment by Eveeifyeve** [comment]
> Any progress since then?

Not really as it doesn't work for me at least, others idk.

**Comment by pink10000** [comment]
Alright, I think I found a fix. Updating it to the most recent commit fixes it.

`4d7d3b10ee1814880514728bd18ffac143329642`

**Comment by Eveeifyeve** [comment]
I will look to updating the latest rev.

**Comment by Aetherall** [comment]
I'm soon allocating more time to tidy up my setup, I will give it another shot within this month, hopefully that commit will do the trick !

**Comment by Eveeifyeve** [comment]
I will look into this to see if it will work with the hm module for now, but I am working on a module system similar to nixvim but for vscode called [nixcode.](https://github.com/nixlify/nixcode)

**Comment by adminy** [comment]
@Eveeifyeve how does your solution fix apc write perms on vscode exec?

**Comment by Eveeifyeve** [comment]
> @Eveeifyeve how does your solution fix apc write perms on vscode exec?

Well first of all it fixes a lot of the issues one it will provide the extension in vscode plus some additional overrides. And second it's going to be easy for beginners that only know nix. And third if you care it's based on the module system.

**Comment by Aneeqasif** [comment]
how you guyz are doing it on nix. any updates on using apc extension on nix?
