### ISSUE TITLE
 devtools   TypeError: findVariable is not a function or its return value is not iterable  

### ISSUE THREAD

**Issue by alaric8** [drcika/apc-extension#184]
auxiliary.js:31 TypeError: findVariable is not a function or its return value is not iterable
    at exports.style (classes.js:206:25)
    at y._invokeFactory (workbench.js:1395:29)
    at y.complete (workbench.js:1405:21)
    at g._onModuleComplete (workbench.js:2021:11)
    at g._resolve (workbench.js:1979:10)
    at g.defineModule (workbench.js:1629:9)
    at s (workbench.js:2094:19)
    at patch.js:15:7
    at y._invokeFactory (workbench.js:1395:29)
    at y.complete (workbench.js:1405:21)
    at g._onModuleComplete (workbench.js:2021:11)
    at g._onModuleComplete (workbench.js:2033:12)
    at g._onModuleComplete (workbench.js:2033:12)
    at g._resolve (workbench.js:1979:10)
    at g.defineModule (workbench.js:1629:9)
    at g._onLoad (workbench.js:1708:10)
    at Object.callback (workbench.js:1885:12)
    at v.triggerCallback (workbench.js:847:24)
    at workbench.js:841:65
    at HTMLScriptElement.o (workbench.js:870:5)
exports.traceError @ auxiliary.js:31
auxiliary.js:31 TypeError: Failed to execute 'appendChild' on 'Node': parameter 1 is not of type 'Node'.
    at toggleSettings (layout.activitybar.js:17:56)
    at exports.init (layout.activitybar.js:161:11)
    at exports.init (layout.js:10:21)
    at exports.startup (override.js:10:14)
    at where.<computed> (utils.js:8:26)
    at _.open (workbench.desktop.main.js:sourcemap:2399:120768)
    at async workbench.js:2602:6
exports.traceError @ auxiliary.js:31

**Comment by alaric8** [comment]
![image](https://github.com/drcika/apc-extension/assets/161679330/7ac2b9be-7f73-4fe7-8b3b-6a031a552d35)

**Comment by alaric8** [comment]
版本: 1.89.1 (user setup)
提交: dc96b837cf6bb4af9cd736aa3af08cf8279f7685
日期: 2024-05-07T05:13:33.891Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Windows_NT x64 10.0.19045

**Comment by archetyped** [comment]
Recently encountered the same error when VS Code's Extension's pane stopped loading any results.

Removing this extension and reinstalling VS Code resolved the issue (hopefully for good).

**Comment by alaric8** [comment]
How to solve this problem in Windows
