### ISSUE TITLE
stopped working after vscode latest update 1.94

### ISSUE THREAD

**Issue by ctf0** [drcika/apc-extension#224]
```
Version: 1.94.0-insider
Commit: 6e9d8a281003211220a6732ec538a28c483ff78b
Date: 2024-09-11T05:04:03.124Z
Electron: 30.4.0
ElectronBuildId: 10073054
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Darwin arm64 23.6.0
```

**Comment by ldkrx** [comment]
![image](https://github.com/user-attachments/assets/cca8eec5-ad9f-465d-a4c3-e8bebb6e2916)
Same here

**Comment by TakiGuan** [comment]
Same here

**Comment by ubranch** [comment]
same

**Comment by ryan6416** [comment]
Submitted issue in https://github.com/microsoft/vscode/issues/228377

**Comment by raldisk** [comment]
same here

**Comment by Sn-Kinos** [comment]
It shows `require.main` is `undefined`
```
2024-09-20 15:12:13.349 [error] TypeError: Cannot read properties of undefined (reading 'filename')
    at Object.<anonymous> (/Users/username/.vscode-insiders/extensions/drcika.apc-extension-0.4.1/dist/patch.js:17:52)
    at Module._compile (node:internal/modules/cjs/loader:1373:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1432:10)
    at Module.load (node:internal/modules/cjs/loader:1215:32)
    at Module._load (node:internal/modules/cjs/loader:1031:12)
    at Function.c._load (node:electron/js2c/node_init:2:13801)
    at Function.e._load (file:///Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:172:10870)
    at Function.t._load (file:///Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:164:22459)
    at Function.i._load (file:///Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:156:3161)
    at Module.require (node:internal/modules/cjs/loader:1240:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (/Users/Kinos/.vscode-insiders/extensions/drcika.apc-extension-0.4.1/dist/extension.js:7:17)
    at Module._compile (node:internal/modules/cjs/loader:1373:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1432:10)
    at Module.load (node:internal/modules/cjs/loader:1215:32)
    at Module._load (node:internal/modules/cjs/loader:1031:12)
    at Function.c._load (node:electron/js2c/node_init:2:13801)
    at Function.e._load (file:///Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:172:10870)
    at Function.t._load (file:///Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:164:22459)
    at Function.i._load (file:///Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:156:3161)
    at Module.require (node:internal/modules/cjs/loader:1240:19)
    at require (node:internal/modules/helpers:179:18)
    at sB.xb (file:///Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:164:23797)
    at async Promise.all (index 0)
    ```

**Comment by jlabs** [comment]
I had to revert to 1.92 for VSCode so I could use VSCode and this extension.

When updating to VSCode 1.93, VSCode would start first time then I'd get a "VSCode needs to restart" like message. If I allowed VSCode to restart it wouldn't return (it appeared the extension was running though). If VSCode was closed then it wouldn't start again until it was back on 1.92.

I've removed the extension for now, but do hope the issue is fixed.

**Comment by ctf0** [comment]
for now we can use `be5invis.vscode-custom-css`
