### ISSUE TITLE
Version 0.0.4 and 0.0.5 are not working

### ISSUE THREAD

**Issue by GXFG** [drcika/apc-extension#7]
Version 0.0.4 and 0.0.5 have errors and have already tried to reinstall. It returned to version 0.03 and is now working normally. 
It looks like the new version is still fetching files from the old version (0.0.3).

The error：
workbench.js:947 GET vscode-file://vscode-app/Users/xxxx/.vscode/extensions/drcika.apc-extension-0.0.3/modules/main.js net::ERR_FILE_NOT_FOUND

browser.main.js:13 Error: [object Event]
    at Object.g [as ensureError] (workbench.js:524:24)
    at p._createLoadError (workbench.js:1748:35)
    at p._onLoadError (workbench.js:1759:32)
    at a (workbench.js:1902:26)
    at Object.errorback (workbench.js:1922:25)
    at g.triggerErrorback (workbench.js:891:36)
    at workbench.js:878:116
    at HTMLScriptElement.o (workbench.js:911:17)

**Comment by drcika** [comment]
this is a caching issue, i hope it's fixed now
